### ISSUE TITLE
请求失败停止运行

### ISSUE THREAD

**Issue by HeiZiSama** [zhixiaobai/Python-zhihuishu#7]
正在查询当前视频学习情况。。。。
开始检测。。。。

视频名称：飞机界定——何谓飞机
视频总时长：00:05:32
学习总时长：5s
状态：未完成
视频名称：腾空而起——飞机升空的秘密
视频总时长：00:15:31
学习总时长：0s
状态：未完成
视频名称：大肚能容——机身（上）
视频总时长：00:09:02
学习总时长：0s
状态：未完成
视频名称：飞机腿脚——起落装置
视频总时长：00:05:05
学习总时长：0s
状态：未完成
视频名称：民机主力---运输飞机
视频总时长：00:04:11
学习总时长：0s
状态：未完成
视频名称：螺旋桨飞机
视频总时长：00:05:51
学习总时长：0s
状态：未完成
视频名称：飞机按外形布局分
视频总时长：00:10:41
学习总时长：0s
状态：未完成
请求失败！停止运行
视频名称：一马当先——波音家族
视频总时长：00:10:16
学习总时长：0s
状态：未完成
视频名称：火眼金睛——辨认波音和空客飞机
视频总时长：00:07:49
学习总时长：0s
状态：未完成
请求失败！停止运行
视频名称：发动机布局及进气口形状
视频总时长：00:05:21
学习总时长：0s
状态：未完成
视频名称：螺旋魅力——螺旋桨系列
视频总时长：00:10:02
学习总时长：0s
状态：未完成
视频名称：美军机命名---机种号
视频总时长：00:09:21
学习总时长：0s
状态：未完成
视频名称：常规布局
视频总时长：00:07:04
学习总时长：0s
状态：未完成
视频名称：空军一号---B747
视频总时长：00:13:08
学习总时长：0s
状态：未完成
请求失败！停止运行

后面很多都是类似的

**Comment by zhixiaobai** [comment]
好兄弟 你要是不介意的话 可以把cookie和secret码发一下 我帮你跑一下看看

**Comment by HeiZiSama** [comment]
> 好兄弟 你要是不介意的话 可以把 cookie和secret码发一下 我帮你跑一下看看

加你扣啦，我是1318185638
